#!/usr/bin/env bash
# Link this repo into place.
#
#   ./install.sh            link everything
#   ./install.sh --dry-run  show what would happen, touch nothing
#
# Idempotent: an existing correct symlink is left alone, and anything real
# that is in the way is moved to <path>.backup-<timestamp> rather than
# deleted. Nothing is ever overwritten silently.

set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}"
STAMP="$(date +%Y%m%d-%H%M%S)"
DRY=0
[[ ${1:-} == --dry-run ]] && DRY=1

link() {
    local src=$1 dst=$2
    if [[ -L $dst && "$(readlink "$dst")" == "$src" ]]; then
        printf '  ok       %s\n' "${dst/#$HOME/\~}"
        return
    fi
    if [[ -e $dst || -L $dst ]]; then
        printf '  backup   %s -> %s.backup-%s\n' "${dst/#$HOME/\~}" "${dst/#$HOME/\~}" "$STAMP"
        (( DRY )) || mv "$dst" "$dst.backup-$STAMP"
    fi
    printf '  link     %s\n' "${dst/#$HOME/\~}"
    (( DRY )) || { mkdir -p "$(dirname "$dst")"; ln -s "$src" "$dst"; }
}

echo "dotfiles: $DOTFILES"
(( DRY )) && echo "(dry run — nothing will be changed)"

# ── ~/.config ────────────────────────────────────────────────────────────
# Every directory in config/ maps to the same name under ~/.config, except
# vscode/, whose contents belong inside Code/User instead.
echo
echo "$CONFIG"
for src in "$DOTFILES"/config/*; do
    name="$(basename "$src")"
    [[ $name == vscode ]] && continue
    link "$src" "$CONFIG/$name"
done

# ── VS Code ──────────────────────────────────────────────────────────────
# Linked file by file: the rest of Code/User is state, not configuration.
echo
echo "VS Code"
for f in settings.json keybindings.json snippets; do
    [[ -e "$DOTFILES/config/vscode/$f" ]] && link "$DOTFILES/config/vscode/$f" "$CONFIG/Code/User/$f"
done

# ── ~/.local/bin ─────────────────────────────────────────────────────────
echo
echo "$HOME/.local/bin"
link "$DOTFILES/local/bin" "$HOME/.local/bin"

# ── NixOS ────────────────────────────────────────────────────────────────
# Root-owned, so this one needs sudo and is left to you. hardware-configuration
# .nix stays a real file on purpose — it describes this machine, and yours
# should come from `nixos-generate-config`.
echo
echo "NixOS (run manually — needs root)"
echo "  sudo mv /etc/nixos/configuration.nix /etc/nixos/configuration.nix.orig"
echo "  sudo ln -s $DOTFILES/nixos/configuration.nix /etc/nixos/configuration.nix"

cat <<'EOF'

Not linked, deliberately:
  gtk-3.0/  gtk-4.0/  swaylock/   generated by the shell, and their writers use
                                  atomic writes, which replace a symlink with a
                                  regular file. They regenerate on first run.
EOF
