#!/usr/bin/env bash
# Point the toolkits at a cursor theme.
#
#   set-cursor.sh Bibata-Modern-Ice 24
#
# niri's own pointer is not set here — that lives in the `cursor` block of
# config.kdl, which NiriTheme.qml writes. config.kdl has one writer on purpose;
# a second one racing it is how hand edits get clobbered. This covers the
# clients instead:
#
#   ~/.icons/default/index.theme   the Xcursor fallback, read by Qt, GTK, and
#                                  anything using libXcursor directly
#   gsettings                      GTK 3/4 and libadwaita, live over dconf
#   gtk-3.0/gtk-4.0 settings.ini   for GTK apps started without a dconf daemon
#
# Apps already running mostly pick up the gsettings change immediately. Ones
# that read the theme once at startup — Electron, anything on plain libXcursor
# — keep the old pointer until they restart. That is a client limitation, not
# something this script can work around.

set -euo pipefail

THEME="${1:?usage: set-cursor.sh <theme> [size]}"
SIZE="${2:-24}"

# ── Xcursor fallback ────────────────────────────────────────────────────
mkdir -p "$HOME/.icons/default"
cat > "$HOME/.icons/default/index.theme" <<EOF
# Generated by the quickshell bar — do not edit.
# Source: ~/.config/quickshell/scripts/set-cursor.sh
[Icon Theme]
Name=Default
Comment=Default cursor theme
Inherits=$THEME
EOF

# ── GTK, live ───────────────────────────────────────────────────────────
if command -v gsettings >/dev/null 2>&1; then
    gsettings set org.gnome.desktop.interface cursor-theme "$THEME" 2>/dev/null || true
    gsettings set org.gnome.desktop.interface cursor-size "$SIZE" 2>/dev/null || true
fi

# ── GTK, on disk ────────────────────────────────────────────────────────
# Rewritten in place so the rest of settings.ini — which GtkTheme.qml owns when
# its toggle is on — survives. Only the two cursor keys are touched.
for ver in 3.0 4.0; do
    ini="$HOME/.config/gtk-$ver/settings.ini"
    [[ -f $ini ]] || continue
    python3 - "$ini" "$THEME" "$SIZE" <<'PY'
import re, sys
path, theme, size = sys.argv[1], sys.argv[2], sys.argv[3]
with open(path) as fh:
    text = fh.read()

for key, value in (("gtk-cursor-theme-name", theme), ("gtk-cursor-theme-size", size)):
    line = f"{key}={value}"
    if re.search(rf"^{key}=", text, re.M):
        text = re.sub(rf"^{key}=.*$", line, text, flags=re.M)
    elif "[Settings]" in text:
        text = text.replace("[Settings]", f"[Settings]\n{line}", 1)
    else:
        text = f"[Settings]\n{line}\n" + text

with open(path, "w") as fh:
    fh.write(text)
PY
done

echo "cursor: $THEME at ${SIZE}px"
