pragma Singleton

import QtQuick
import Quickshell
import "root:/"
import Quickshell.Io

// Pushes the flavour out to GTK apps — Thunar, file pickers, GTK dialogs.
//
// Two mechanisms, because they cover different apps: gsettings is what GTK4
// and libadwaita read at runtime, while the settings.ini files are what GTK3
// apps read at startup. Writing both means running apps follow along where
// they can, and everything else is right the next time it opens.
Singleton {
    id: root

    readonly property bool enabled: Settings.themeGtk

    // Latte is the only light flavour; everything else is dark.
    readonly property bool light: Settings.flavour === "latte"

    readonly property string colorScheme: root.light ? "prefer-light" : "prefer-dark"
    readonly property string iconTheme: root.light ? "Papirus" : "Papirus-Dark"

    // Accent is fixed at mauve because configuration.nix builds one GTK theme
    // per flavour, not per flavour-and-accent. Falls back to whichever variant
    // is present if the others have not been built yet.
    readonly property var gtkThemes: ({
            mocha: "catppuccin-mocha-mauve-standard",
            macchiato: "catppuccin-macchiato-mauve-standard",
            frappe: "catppuccin-frappe-mauve-standard",
            latte: "catppuccin-latte-mauve-standard"
        })

    readonly property string gtkTheme: root.gtkThemes[Settings.flavour] ?? "catppuccin-mocha-mauve-standard"

    function apply() {
        if (!root.enabled)
            return;

        setter.exec(["sh", "-c", `
            gsettings set org.gnome.desktop.interface color-scheme '${root.colorScheme}'
            gsettings set org.gnome.desktop.interface icon-theme '${root.iconTheme}'
            gsettings set org.gnome.desktop.interface gtk-theme '${root.gtkTheme}'
            true
        `]);

        gtk3.setText(root._ini());
        gtk4.setText(root._ini());
    }

    function _ini() {
        return `# Generated by the quickshell bar — do not edit.
# Source: ~/.config/quickshell/services/GtkTheme.qml
[Settings]
gtk-theme-name=${root.gtkTheme}
gtk-icon-theme-name=${root.iconTheme}
gtk-font-name=Noto Sans 10
gtk-application-prefer-dark-theme=${root.light ? 0 : 1}
`;
    }

    onEnabledChanged: settle.restart()
    onColorSchemeChanged: settle.restart()
    onGtkThemeChanged: settle.restart()
    onIconThemeChanged: settle.restart()

    Timer {
        id: settle
        interval: 250
        onTriggered: root.apply()
    }

    Process {
        id: setter
    }

    FileView {
        id: gtk3
        path: `${Quickshell.env("HOME")}/.config/gtk-3.0/settings.ini`
        atomicWrites: true
        printErrors: false
    }

    FileView {
        id: gtk4
        path: `${Quickshell.env("HOME")}/.config/gtk-4.0/settings.ini`
        atomicWrites: true
        printErrors: false
    }

    Component.onCompleted: settle.restart()
}
