pragma Singleton

import QtQuick
import Quickshell
import "root:/"
import Quickshell.Io

// Keeps kitty's colours in step with the bar.
//
// kitty.conf `include`s colors.conf, which is written here from the selected
// Catppuccin flavour and accent. Running terminals reload their config on
// SIGUSR1, so a flavour change lands in windows that are already open rather
// than only in the next one.
Singleton {
    id: root

    readonly property string confPath: `${Quickshell.env("HOME")}/.config/kitty/colors.conf`

    readonly property bool enabled: Settings.themeTerminal

    // Rebuilt whenever the flavour, accent or terminal opacity changes.
    readonly property string conf: root._render(Theme.palette, Theme.accentFor(Settings.accent), Settings.terminalOpacity)

    function _render(p, accent, opacity) {
        return `# Generated by the quickshell bar — do not edit.
# Source: ~/.config/quickshell/services/KittyTheme.qml
# Flavour: ${Settings.flavour}   Accent: ${Settings.accent}

foreground              ${p.text}
# crust, not base: this is what Theme.barBg uses, so the terminal sits on the
# same tier as the bar and the panels rather than a lighter one.
background              ${p.crust}
selection_foreground    ${p.crust}
selection_background    ${p.rosewater}

# Its own setting, not the bar's: dynamic_background_opacity is required for
# kitty to honour a change to this on reload rather than only at startup.
dynamic_background_opacity yes
background_opacity      ${opacity.toFixed(2)}

cursor                  ${accent}
cursor_text_color       ${p.base}

url_color               ${accent}

active_border_color     ${accent}
inactive_border_color   ${p.surface2}
bell_border_color       ${p.yellow}

wayland_titlebar_color  ${p.crust}

active_tab_foreground   ${p.crust}
active_tab_background   ${accent}
inactive_tab_foreground ${p.text}
inactive_tab_background ${p.mantle}
tab_bar_background      ${p.crust}

# Black
color0  ${p.surface1}
color8  ${p.surface2}
# Red
color1  ${p.red}
color9  ${p.red}
# Green
color2  ${p.green}
color10 ${p.green}
# Yellow
color3  ${p.yellow}
color11 ${p.yellow}
# Blue
color4  ${p.blue}
color12 ${p.blue}
# Magenta
color5  ${p.pink}
color13 ${p.pink}
# Cyan
color6  ${p.teal}
color14 ${p.teal}
# White
color7  ${p.subtext1}
color15 ${p.subtext0}
`;
    }

    onConfChanged: if (root.enabled)
        writeDelay.restart()
    onEnabledChanged: if (root.enabled)
        writeDelay.restart()

    // Dragging the opacity slider would otherwise spawn a write and a signal
    // per frame.
    Timer {
        id: writeDelay
        interval: 250
        onTriggered: {
            confFile.setText(root.conf);
            reloader.running = true;
        }
    }

    FileView {
        id: confFile
        path: root.confPath
        atomicWrites: true
        printErrors: false
    }

    // `set-colors` rather than SIGUSR1. A reload signal makes kitty re-read
    // its config, but it does not repaint the background of windows that are
    // already open — which is why terminals had to be restarted by hand.
    // set-colors --all --configured pushes the new palette into every live
    // window and updates what new ones will use.
    //
    // Opacity is a separate call; it needs dynamic_background_opacity, which
    // colors.conf sets.
    //
    // SIGUSR1 stays as a fallback for any instance started before remote
    // control was enabled. Matched on the command line, not the process name:
    // under Nix the comm is ".kitty-wrapped", so `pkill -x kitty` matches
    // nothing. The anchor keeps it off the `kitten` helpers.
    Process {
        id: reloader
        command: ["sh", "-c", `
            k="kitty @ --to unix:@mykitty"
            $k set-colors --all --configured ${root.confPath} 2>/dev/null
            $k set-background-opacity --all ${Settings.terminalOpacity.toFixed(2)} 2>/dev/null
            pkill -USR1 -f '^kitty( |\$)' 2>/dev/null
            true
        `]
    }

    // Write once at startup so the file exists and matches the current
    // settings even if nothing changes this session.
    Component.onCompleted: if (root.enabled)
        writeDelay.restart()
}
