pragma Singleton

import QtQuick
import Quickshell
import "root:/"
import Quickshell.Io

// Colours the lock screen to match the flavour and accent.
//
// swaylock reads its config only at launch, and it is launched fresh every
// time the screen locks, so there is nothing to signal — writing the file is
// enough for the next lock to pick it up.
//
// swaylock wants colours as bare RRGGBB or RRGGBBAA with no leading '#'.
Singleton {
    id: root

    readonly property bool enabled: Settings.themeSwaylock

    function _hex(c) {
        return String(c).replace("#", "");
    }

    function _render() {
        const p = Theme.palette;
        const accent = root._hex(Theme.accentFor(Settings.accent));

        return `# Generated by the quickshell bar — do not edit.
# Source: ~/.config/quickshell/services/SwaylockTheme.qml

daemonize
ignore-empty-password
show-failed-attempts
indicator-radius=100
indicator-thickness=8

color=${root._hex(p.crust)}

inside-color=${root._hex(p.base)}
inside-clear-color=${root._hex(p.surface0)}
inside-ver-color=${root._hex(p.surface0)}
inside-wrong-color=${root._hex(p.surface0)}

ring-color=${accent}
ring-clear-color=${root._hex(p.yellow)}
ring-ver-color=${root._hex(p.sapphire)}
ring-wrong-color=${root._hex(p.red)}

key-hl-color=${root._hex(p.green)}
bs-hl-color=${root._hex(p.red)}

text-color=${root._hex(p.text)}
text-clear-color=${root._hex(p.text)}
text-ver-color=${root._hex(p.text)}
text-wrong-color=${root._hex(p.text)}

line-color=00000000
line-clear-color=00000000
line-ver-color=00000000
line-wrong-color=00000000

separator-color=00000000
`;
    }

    readonly property string conf: root._render()

    onConfChanged: if (root.enabled)
        settle.restart()
    onEnabledChanged: if (root.enabled)
        settle.restart()

    Timer {
        id: settle
        interval: 250
        onTriggered: file.setText(root.conf)
    }

    FileView {
        id: file
        path: `${Quickshell.env("HOME")}/.config/swaylock/config`
        atomicWrites: true
        printErrors: false
    }

    Component.onCompleted: if (root.enabled)
        settle.restart()
}
